version: "3"
services:
  app:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      URL: http://lista.mercadolivre.com.br/
      PORT: 3000
    ports:
      - 3000:3000
    command: npm start
